jQuery(document).ready(function(a){function g(b,c,d){""==b&&(b="0");a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:b,save:1,use_core:c,use_ui:d,_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Saving...")},success:function(b,c,d){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):return_error(d.process,b.message)}})}a("#fc_use_ui").unbind("click").click(function(b){b.preventDefault();b=a("#fc_headers_pageid").text();
a(this).is(":checked")&&a("#fc_use_core").prop("checked",!0);g(b,a("#fc_use_core").is(":checked"),a("#fc_use_ui").is(":checked"))});a("#fc_use_core").unbind("click").click(function(b){b.preventDefault();b=a("#fc_headers_pageid").text();a(this).not(":checked")&&a("#fc_use_ui").prop("checked",!1);g(b,a("#fc_use_core").is(":checked"),a("#fc_use_ui").is(":checked"))});a("form#settings.ajax_form ul#fc_pages_headerfiles_js ul.ui-sortable").children().length&&a("#fc_use_core").prop("checked",!0);a("form#settings.ajax_form ul#fc_pages_headerfiles_js ul.ui-sortable").children().length&&
a("#fc_use_core").prop("checked",!0);a("button.fcAddPlugin").length&&a("button.fcAddPlugin").unbind("click").click(function(b){b.preventDefault();var c=a("#fc_headers_pageid").text();""===c&&(c=0);a("div#dlgAddPlugin").dialog({modal:!0,title:cattranslate("Add jQuery Plugin"),width:600,height:250,buttons:[{text:cattranslate("Save"),click:function(){a(this).dialog("close");a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:c,add_plugin:a("div#dlgAddPlugin").find("select:first").val(),
_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Adding...")},success:function(b,c,e){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):return_error(e.process,b.message)}})}},{text:cattranslate("Close"),click:function(){a(this).dialog("close")}}]})});a("button.fcDelPlugin").length&&a("button.fcDelPlugin").unbind("click").click(function(b){b.preventDefault();var c=a("#fc_headers_pageid").text();""===c&&(c=0);a("div#dlgAddPlugin").find("span.warning").hide();
a("div#dlgAddPlugin").dialog({modal:!0,width:600,height:250,title:cattranslate("Remove plugin"),buttons:[{text:cattranslate("Save"),click:function(){a(this).dialog("close");a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:c,del_plugin:a("div#dlgAddPlugin").find("select:first").val(),_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Removing...")},success:function(b,c,e){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):
return_error(e.process,b.message)}})}},{text:cattranslate("Close"),click:function(){a(this).dialog("close")}}]})});a("#fc_pages_headerfiles_js").length&&(a("ul.ui-sortable").sortable({items:"> li",axis:"y",cursor:"move",helper:"original",placeholder:"fc_sortable_placeholder fc_gradient1 fc_br_all fc_shadow_small",forceHelperSize:!0,update:function(b,c){var d={order:a(this).sortable("toArray"),page_id:a("#fc_headers_pageid").text(),type:c.item.prop("class").replace("page_",""),_cat_ajax:1};a.ajax({type:"POST",
url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:d,cache:!1,beforeSend:function(a){a.process=set_activity("Reorder...")},success:function(b,c,d){a(".popup").dialog("destroy").remove();!0===b.success?return_success(d.process,b.message):return_error(d.process,b.message)}})}}).disableSelection(),a("button#fcAddJS").unbind("click").click(function(b){b.preventDefault();var c=a("#fc_headers_pageid").text();""===c&&(c=0);a("div#dlgAddJS").dialog({modal:!0,width:600,height:150,buttons:[{text:cattranslate("Save"),
click:function(){a(this).dialog("close");a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:c,add_js_file:a("div#dlgAddJS").find("select:first").val(),_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Adding...")},success:function(b,c,e){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):return_error(e.process,b.message)}})}},{text:cattranslate("Close"),click:function(){a(this).dialog("close")}}]})}),a(".fcDelJS").unbind("click").click(function(b){b.preventDefault();
b=a("#fc_headers_pageid").text();""===b&&(b=0);a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:b,del_js_file:a(this).parent().prop("id"),_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Remove...")},success:function(b,d,f){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):return_error(f.process,b.message)}})}));a("#fc_pages_headerfiles_css").length&&(a(".fcAddCSS").unbind("click").click(function(b){b.preventDefault();
var c=a("#fc_headers_pageid").text();""===c&&(c=0);a("div#dlgAddCSS").dialog({modal:!0,width:600,height:150,buttons:[{text:cattranslate("Save"),click:function(){a(this).dialog("close");a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:c,add_css_file:a("div#dlgAddCSS").find("select:first").val(),_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Adding...")},success:function(b,c,e){a(".popup").dialog("destroy").remove();!0===b.success?location.reload(!0):
return_error(e.process,b.message)}})}},{text:cattranslate("Close"),click:function(){a(this).dialog("close")}}]})}),a(".fcDelCSS").unbind("click").click(function(b){b=a("#fc_headers_pageid").text();""===b&&(b=0);a.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_headers.php",dataType:"json",data:{page_id:b,del_css_file:a(this).parent().prop("id"),_cat_ajax:1},cache:!1,beforeSend:function(a){a.process=set_activity("Remove...")},success:function(b,d,f){a(".popup").dialog("destroy").remove();!0===b.success?
location.reload(!0):return_error(f.process,b.message)}})}))});
