/*
       2014, Black Cat Development
   @link            http://blackcat-cms.org
   @license         http://www.gnu.org/licenses/gpl.html
   @category        CAT_Core
   @package         freshcat

*/
jQuery(document).ready(function(){0===$("#fc_main_content").size()&&$("#fc_content_container").wrapInner('<div id="fc_main_content" />');$(".fc_toggle_section_block").click(function(){var a=$(this),b=a.parents(".fc_module_block"),c=SESSION+b.prop("id");b.toggleClass("fc_active");b.hasClass("fc_active")?($.cookie(c,"open",{path:"/"}),a.switchClass("icon-eye-blocked-2","icon-eye-2"),b.find(".fc_blocks_content").slideDown(300)):($.cookie(c,"closed",{path:"/"}),a.switchClass("icon-eye-2","icon-eye-blocked-2"),
b.find(".fc_blocks_content").slideUp(300))});$(".fc_module_block").each(function(){var a=$(this),b=a.attr("id");getCoo=SESSION+b;"undefined"!==typeof $.cookie(getCoo)&&"closed"==$.cookie(getCoo)&&a.find(".fc_toggle_section_block").click()});$("#hide_modules").click(function(){$(".fc_toggle_section_block").removeClass("fc_active").switchClass("icon-eye-2","icon-eye-blocked-2");$(".fc_module_block").removeClass("fc_active");$(".fc_blocks_content").slideUp(100)});$("#show_modules").click(function(){$(".fc_toggle_section_block").addClass("fc_active").switchClass("icon-eye-blocked-2",
"icon-eye-2");$(".fc_module_block").addClass("fc_active");$(".fc_blocks_content").slideDown(100)});$("#recreate_af").click(function(){dates={page_id:$("div#fc_add_module").find("input[name=page_id]").val(),_cat_ajax:1};$.ajax({type:"POST",url:CAT_ADMIN_URL+"/pages/ajax_recreate_af.php",dataType:"json",data:dates,cache:!1,beforeSend:function(a){a.process=set_activity("Recreating file...");a.block_name=dates.block_name;a.name=dates.name},success:function(a,b,c){var e=$(this);$(".popup").dialog("destroy").remove();
!0===a.success?(return_success(c.process,a.message),e.slideUp(300,function(){e.remove()})):return_error(c.process,a.message)},error:function(a,b,c){-1!=a.responseText.indexOf("fc_login_form")?location.href=CAT_ADMIN_URL+"/login/index.php":($(".popup").dialog("destroy").remove(),alert(b+": "+c))}})});$("#fc_all_blocks").sortable({handle:".fc_section_drag",axis:"y",cursor:"move",helper:"original",placeholder:"fc_sortable_placeholder fc_gradient4 fc_br_all fc_shadow_small",forceHelperSize:!0,start:function(a,
b){if("undefined"!=typeof tinyMCE){tinyids=[];var c=0;$(".mce-tinymce").each(function(){var a=$(this).next("textarea").prop("id");tinyids[c]=a;tinyMCE.execCommand("mceRemoveEditor",!1,a);c++})}"function"==typeof ckeditorOff&&ckeditorOff()},stop:function(a,b){"undefined"!=typeof tinyids&&$.each(tinyids,function(a,b){tinyMCE.execCommand("mceAddEditor",!1,b)});"function"==typeof ckeditorOn&&ckeditorOn()},update:function(a,b){var c={sectionid:$(this).sortable("toArray"),table:"sections"};dialog_ajax("Reorder pages",
CAT_ADMIN_URL+"/pages/ajax_reorder.php",c,"POST","json",!1,!1,!1)}});$(".fc_delete_section").click(function(a){a.preventDefault();0===$(".popup").size()&&$("#fc_admin_header").prepend('<div class="popup" />');$(".popup").html("<p>"+cattranslate("Do you really want to delete this section?")+"</p>");var b=$(this);dates={delete_section_id:b.find("input[name=delete_section_id]").val(),_cat_ajax:1};buttonsOpts=[];buttonsOpts.push({text:cattranslate("Yes"),click:function(){$.ajax({type:"POST",context:b.closest(".fc_module_block"),
url:CAT_ADMIN_URL+"/pages/ajax_sections_save.php",dataType:"json",data:dates,cache:!1,beforeSend:function(a){a.process=set_activity("Save section");a.block_name=dates.block_name;a.name=dates.name},success:function(a,b,d){var f=$(this);$(".popup").dialog("destroy").remove();!0===a.success?(return_success(d.process,a.message),f.slideUp(300,function(){f.remove()})):return_error(d.process,a.message)},error:function(a,b,d){-1!=a.responseText.indexOf("fc_login_form")?location.href=CAT_ADMIN_URL+"/login/index.php":
($(".popup").dialog("destroy").remove(),alert(b+": "+d))}})},"class":"submit"});buttonsOpts.push({text:cattranslate("No"),click:function(){$(".popup").dialog("destroy").remove()},"class":"reset"});$(".popup").dialog({modal:!0,show:"fade",closeOnEscape:!0,title:cattranslate("Delete section"),buttons:buttonsOpts})});$(".fc_open_section_modify").click(function(){$(this).parents(".fc_section_modify_div_parent").children(".fc_section_modify_div").toggle(300)});$(".fc_modify_section input[type=submit]").click(function(a){a.preventDefault();
a=$(this).closest(".fc_section_modify_div_parent");var b={update_section_id:a.find("input[name=update_section_id]").val(),page_id:$("input[name=page_id]").val(),set_block:a.find("select[name=set_block]").val(),blockname:a.find("input[name=blockname]").val(),day_from:a.find("input[name=day_from]").val(),month_from:a.find("input[name=month_from]").val(),year_from:a.find("input[name=year_from]").val(),hour_from:a.find("input[name=hour_from]").val(),minute_from:a.find("input[name=minute_from]").val(),
day_to:a.find("input[name=day_to]").val(),month_to:a.find("input[name=month_to]").val(),year_to:a.find("input[name=year_to]").val(),hour_to:a.find("input[name=hour_to]").val(),minute_to:a.find("input[name=minute_to]").val(),_cat_ajax:1};$.ajax({type:"POST",context:a,url:CAT_ADMIN_URL+"/pages/ajax_sections_save.php",dataType:"json",data:b,cache:!1,beforeSend:function(a){a.process=set_activity("Save section");a.block_name=b.block_name;a.name=b.name},success:function(a,b,d){b=$(this);!0===a.success?
(return_success(d.process,a.message),b.closest(".fc_blocks_header").find(".fc_section_header_block strong").text(a.updated_block),b.closest(".fc_blocks_header").find(".fc_section_header_name strong").text(a.updated_section.name),b.children(".fc_section_modify_div").fadeOut(300)):return_error(d.process,a.message)}})})});
