/*
       2014, Black Cat Development
   @link            http://blackcat-cms.org
   @license         http://www.gnu.org/licenses/gpl.html
   @category        CAT_Core
   @package         freshcat

*/
function get_active_media(){if(0<$("#fc_media_browser .fc_media_folder_active").size())return $("#fc_media_browser .fc_media_folder_active:first");if(0<$("#fc_media_browser .fc_active").size())return $("#fc_media_browser .fc_active:first").hasClass("fc_filetype_file")?$("#fc_media_browser .fc_active:first").closest("ul.fc_media_folder"):$("#fc_media_browser .fc_active:first").closest("ul.fc_media_folder").next("ul.fc_media_folder");$("ul.fc_media_folder:first").addClass("fc_media_folder_active");
return $("ul.fc_media_folder:first")}
function save_name(a,b){"undefined"==typeof b&&(b="");var c=a.parent("li"),e=c.closest("ul.fc_media_folder");b=c.hasClass("fc_filetype_folder")||"undefined"==typeof b?"":b;dates={file_path:e.children("input[name=folder_path]").val(),rename_file:c.children("input[name=load_url]").val(),new_name:a.val(),extension:b,_cat_ajax:1};$.ajax({type:"POST",context:c,url:CAT_ADMIN_URL+"/media/ajax_rename.php",dataType:"json",data:dates,cache:!1,beforeSend:function(b){b.process=set_activity("Save name");a.addClass("fc_name_update_process");
$("#fc_media_info").hide();e.prepend('<li class="fc_loader" />')},success:function(a,b,e){var c=$(this);b=c.closest("ul.fc_media_folder");c=c.children("input[name=rename]");b.children(".fc_loader").remove();!0===a.success?(return_success(e.process,a.message),b.addClass("fc_media_folder_active"),b.children("li").remove(),reload_folder(b)):(return_error(e.process,a.message),c.focus());scrollToRight()}})}
function reload_folder(a,b,c){b={load_url:"undefined"!==typeof c?c:"/",folder_path:"undefined"!==typeof b?b:a.children("input[name=folder_path]").val(),_cat_ajax:1};$.ajax({type:"POST",context:a,url:CAT_ADMIN_URL+"/media/ajax_get_contents.php",dataType:"json",data:b,cache:!1,beforeSend:function(b){$("#fc_media_info").hide();a.nextAll("ul").remove();a.prepend('<li class="fc_loader" />')},success:function(a,b,c){b=$(this);b.children(".fc_loader").remove();a.is_folder?(b.append('<input type="hidden" name="folder_path" value="'+
a.initial_folder+'">'),$("#fc_media_index_upload input[name=folder_path]").val(a.initial_folder),"undefined"==typeof a.folders&&"undefined"==typeof a.files&&$("ul.fc_media_folder_active").append('<li class="icon-info"> '+cattranslate("No files available")+"</li>"),"undefined"!=typeof a.folders&&$.each(a.folders,function(a,b){var c='<li class="fc_filetype_folder" title="'+b.name+'"><div class="fc_name_short"><p class="icon-folder"> '+b.name+'</p></div><input type="hidden" name="load_url" value="'+
encodeURIComponent(b.name)+'" /></li>';$("ul.fc_media_folder_active").append(c)}),"undefined"!=typeof a.files&&$.each(a.files,function(a,b){var c='<li class="fc_filetype_file" title="'+b.full_name+'"><div class="fc_name_short"><p class="icon-file-'+b.filetype+'"> '+b.full_name+'</p></div><input type="hidden" name="load_url" value="'+b.full_name+'" /></li>';$("ul.fc_media_folder_active").append(c)}),b.find(".fc_name_short p").smartTruncation({truncateCenter:!0}),set_media_functions(b),a.is_writable?
($("#fc_media_index_upload").removeClass("hidden"),$("#fc_media_upload_not_writable").addClass("hidden")):($("#fc_media_upload_not_writable").removeClass("hidden"),$("#fc_media_index_upload").addClass("hidden"))):(b=$("#fc_media_info"),a=a.files,b.fadeIn(300),a.show_preview?($(".fc_file_info").children("img").remove(),$(".fc_file_info").children("p").hide(),$(".fc_file_info").prepend('<img src="'+a.load_url+'" alt="'+cattranslate("Preview")+'" />')):($(".fc_file_info").children("p").show(),$(".fc_file_info").children("img").remove()),
b.find(".fc_filename").text(" "+a.filename).removeClass().addClass("fc_filename icon-file-"+a.filetype),b.find(".fc_file_type").text(a.filetype),b.find(".fc_file_size").text(a.filesize),b.find(".fc_file_date").text(a.filedate),b.find(".fc_file_time").text(a.filetime));scrollToRight()}})}function scrollToRight(){var a=$("#fc_media_browser").width();$("#fc_media_browser").animate({scrollLeft:a},0)}
function set_media_functions(a){a.children("li").mouseover(function(){a.removeClass("fc_clickable")}).mouseout(function(){a.addClass("fc_clickable")});a.click(function(){var a=$(this);a.hasClass("fc_clickable")&&($("ul.fc_media_folder_active").removeClass("fc_media_folder_active"),a.addClass("fc_media_folder_active"))});a.children(".fc_filetype_file, .fc_filetype_folder").not(".fc_no_content, .fc_save_rename").unbind("click").click(function(){var a=$(this),c=a.closest("ul.fc_media_folder"),e=a.children("input[name=load_url]").val(),
d=c.children("input[name=folder_path]").val();$("ul.fc_media_folder_active").removeClass("fc_media_folder_active");c.prevAll("ul.fc_media_folder").find(".fc_active").addClass("fc_open_folder").removeClass("fc_active");c.nextAll("ul.fc_media_folder").remove();c.children(".fc_active").removeClass("fc_active");c.children(".fc_open_folder").removeClass("fc_open_folder");a.addClass("fc_active");var f=250*$("ul.fc_media_folder").size();a.hasClass("fc_filetype_folder")?c=$('<ul class="fc_media_folder fc_gradient1 fc_media_folder_active fc_clickable" />').insertAfter(c).css({left:f}):
(c.addClass("fc_media_folder_active"),$("#fc_media_info").css({left:f}));reload_folder(c,d,e)})}
function copy_upload_field(a){var b=a.children("input[type=file]");a.find(".fc_upload_close").click(function(){a.closest(".fc_upload_fields").remove();1<$("#fc_media_index_upload").find("input[type=file]").size()?$(".fc_upload_field:last").removeClass("fc_inactive"):(add_new_upload_field(),$(".fc_upload_field:first").addClass("fc_inactive"))});b.change(function(){var c=b.val(),e=c.substr(c.lastIndexOf("\\")+1),c=c.substr(c.lastIndexOf(".")+1).toLowerCase(),d=b.prop("accept").split("|");if(-1<jQuery.inArray(c,
d))switch(a.children("input[type=text]").val(e),a.hasClass("fc_inactive")||(add_new_upload_field(),a.addClass("fc_inactive")),c){case "zip":case "rar":case "gz":a.next(".fc_upload_zip").removeClass("hidden");break;default:a.next(".fc_upload_zip").addClass("hidden")}else a.switchClass("fc_gradient4","fc_gradient_red",300),setTimeout(function(){a.switchClass("fc_gradient_red","fc_gradient4",3E3)},1200)})}
function add_new_upload_field(){var a=parseInt($("#fc_media_index_upload .fc_upload_fields:last").children("input[name^=upload_counter]").val(),10)+1,b=$("#fc_upload_field_add > div").clone().removeClass("hidden").insertAfter("#fc_media_index_upload .fc_upload_fields:last");b.children("input[name^=upload_counter]").val(a);b.find("input[type=file]").prop("name","upload_"+a);b.find("input[name=unzip_]").prop("name","unzip_"+a).prop("id","unzip_"+a).addClass("show___fc_delete_zip_div_"+a).next("label").prop("for",
"unzip_"+a);b.find("input[name=delete_zip_]").prop("name","delete_zip_"+a).prop("id","delete_zip_"+a).next("label").prop("for","delete_zip_"+a).closest("div").prop("id","fc_delete_zip_div_"+a);b.find(".fc_toggle_element").fc_toggle_element();copy_upload_field(b.children(".fc_upload_field"))}
jQuery(document).ready(function(){$("#fc_upload_button").click(function(){$(".fc_upload_field").remove();add_new_upload_field(!1)});copy_upload_field($("#fc_media_index_upload .fc_upload_field:first"));$("#fc_add_upload_field").click(function(){add_new_upload_field($(".fc_upload_field:last"))});$("#fc_header_button_dropdown_toggle a").click(function(a){a.preventDefault();$("#fc_media_index_upload_ul").toggle(300);$(this).toggleClass("fc_active",300)});$("#fc_close_media").click(function(){var a=$("#fc_media_index_upload");
a.children(".fc_upload_fields:first").nextAll(".fc_upload_fields").remove();a.find(".fc_upload_field").removeClass("fc_inactive");a.find(".fc_toggle_element").prop("checked",!1).click();a.find(".fc_upload_zip").addClass("hidden");$("#fc_header_button_dropdown_toggle a").click()});$(".fc_name_short p").smartTruncation({truncateCenter:!0});set_media_functions($("ul.fc_media_folder"));$(".fc_delete_file").unbind().click(function(a){a.preventDefault();if(0===$("#fc_media_browser li.fc_active").size())$(this).addClass("fc_inactive_button");
else{a=$("#fc_media_browser li.fc_active");if(a.hasClass("fc_filetype_file")){var b="<br/><strong>"+a.find(".fc_name_short").text()+"</strong>";cattranslate("Are you sure you want to delete file {name}").replace(/\{name\}/g,b);b="file"}else b="<br/><strong>"+a.find(".fc_name_short").text()+"</strong>",cattranslate("Are you sure you want to delete the directory {name}").replace(/\{name\}/g,b),b="folder";var c={load_url:a.children("input[name=load_url]").val(),file_path:a.closest("ul.fc_media_folder").find("input[name=folder_path]").val(),
file:a.find("input[name=load_url]").val(),type:b,_cat_ajax:1};dialog_confirm(cattranslate("Do you really want to delete this "+b+"?"),cattranslate("Delete "+b),CAT_ADMIN_URL+"/media/ajax_delete.php",c,"POST","JSON",function(a){$("#fc_media_browser li.fc_active").closest("ul").prepend('<li class="fc_loader" />');$("#fc_media_info").hide()},function(a,b,c){$("li.fc_loader").remove();!0===a.success?(a=$(this),b=a.closest("ul"),c=a.parent().parent().prop("id"),1==b.children("li").size()?("fc_media_browser"!=
c?b.nextAll("ul.fc_media_folder").andSelf().remove():(b.nextAll("ul.fc_media_folder").remove(),b.html('<ul class="fc_media_folder fc_media_folder_active fc_clickable">    <input type="hidden" value="'+b.find('input[name="folder_path"]').val()+'" name="folder_path">    <li class="fc_filetype_file fc_no_content">'+cattranslate("No files available")+"</li></ul>")),b=$(".fc_open_folder:last"),b.closest("ul").removeClass("fc_clickable")):(a.hasClass("fc_filetype_folder"),b.nextAll("ul.fc_media_folder").remove()),
b.click(),a.remove()):return_error(c.process,a.message)},a)}});$(".fc_rename_file").unbind().click(function(){var a=$("#fc_media_browser .fc_active"),b=a.children("input[name=load_url]").val(),c=a.hasClass("fc_filetype_folder")?b:b.substr(0,b.lastIndexOf(".")),e=a.hasClass("fc_filetype_folder")?"":b.substr(b.lastIndexOf(".")+1),d=$('<input type="text" name="rename" value="'+c+'" />').appendTo(a).slideUp(0).slideDown(200).focus(),b=$('<span class="icon-checkmark fc_gradient1 fc_gradient_hover fc_border fc_save_rename" />').appendTo(a).click(function(a){d.addClass("fc_name_update_process");
save_name(d,e)});a.children(".fc_name_short").slideUp(0);d.keydown(function(a){"13"==a.keyCode&&save_name(d,e)});b.mouseenter(function(){d.addClass("fc_name_update_process")}).mouseleave(function(){d.removeClass("fc_name_update_process")});d.focusout(function(){d.hasClass("fc_name_update_process")||save_name(d,e)})});$(".fc_create_new_folder").unbind().click(function(){$(document).delegate(".ui-dialog","keyup",function(a){var b=a.target.tagName.toLowerCase(),b="input"===b&&"button"===a.target.type?
"button":b;if(a.which===$.ui.keyCode.ENTER&&"textarea"!==b&&"select"!==b&&"button"!==b)return $(this).find(".ui-dialog-buttonset button").eq(0).trigger("click"),!1});$('<div><input type="text" name="fc_media_add_folder_name" style="width:100%" value="" /></div>').dialog({autoOpen:!1,width:300,height:180,title:cattranslate("Folder name"),buttons:[{text:cattranslate("Save"),click:function(){$(this).dialog("close");var a=get_active_media(),b={folder_path:a.children("input[name=folder_path]").val(),name:$(this).find("input:first").val(),
_cat_ajax:1};$.ajax({type:"POST",context:a,url:CAT_ADMIN_URL+"/media/ajax_create_folder.php",dataType:"json",data:b,cache:!1,beforeSend:function(b){b.process=set_activity("Create folder");$("#fc_media_info").hide();a.children("li").remove().prepend('<li class="fc_loader" />')},success:function(b,e,d){a.children(".fc_loader").remove();!0===b.created?(return_success(d.process,b.message),reload_folder(a)):return_error(d.process,b.message)}})}},{text:cattranslate("Cancel"),click:function(){$(this).dialog("close")}}]}).dialog("open");
return!1});dialog_form($("#fc_media_index_upload"),function(a){a=get_active_media().find("input[name=folder_path]").val();$("#fc_media_index_upload input[name=folder_path]").val(a)},function(a,b,c){a=$("#fc_media_index_upload");b=get_active_media();b.children("li").remove();reload_folder(b);a.children(".fc_upload_fields:first").nextAll(".fc_upload_fields").remove();a.find(".fc_upload_field").removeClass("fc_inactive");a.find(".fc_toggle_element").prop("checked",!1).click();a.find(".fc_upload_zip").addClass("hidden");
$("#fc_media_index_upload").find('input[type="reset"]').click()})});
