/*
       2014, Black Cat Development
   @link            http://blackcat-cms.org
   @license         http://www.gnu.org/licenses/gpl.html
   @category        CAT_Core
   @package         freshcat

*/
(function(a){a.fn.set_individual_buttons=function(e){e=a.extend({standard_class:"fc_checkbox_jq",individual_class:"fc_checkbox_ind"},e);var d=function(b){var c=match_class_prefix("set_advanced___",b),c=a("#"+c);c.children("input").size()==c.children("input:checked").size()?b.prop("checked",!0).addClass(e.standard_class).removeClass(e.individual_class):c.children("input").size()==c.children("input").not(":checked").size()?b.prop("checked",!1).addClass(e.standard_class).removeClass(e.individual_class):
b.prop("checked",!0).addClass(e.individual_class).removeClass(e.standard_class)};return this.each(function(){var b=a(this),c=match_class_prefix("set_advanced___",b),f=a("#"+c);f.children("input").click(function(){d(b)});b.change(function(){var a=b.is(":checked");f.children("input").prop("checked",a);d(b)});d(b)})}})(jQuery);
(function(a){a.fn.set_list_click=function(e){var d={get_url:CAT_ADMIN_URL+"/groups/ajax_get_group.php",activity_message:"Loading group",addOnly:a(".fc_addGroup"),modifyOnly:a(".fc_modifyGroup"),get_id:"group_id"};e=a.extend(d,e);return this.each(function(){a(this).click(function(b){b.preventDefault();b=a(this);var c={id:b.children("input[name="+e.get_id+"]").val(),_cat_ajax:1};a.ajax({type:"POST",context:b,url:e.get_url,dataType:"JSON",data:c,cache:!1,beforeSend:function(a){a.process=set_activity(e.activity_message)},
success:function(b,c,d){c=a(this);c.closest("ul").children("li").not(c).removeClass("fc_active");a("#fc_list_add").removeClass("fc_active");c.addClass("fc_active");!0===b.success?(e.addOnly.hide(),e.modifyOnly.show(),c=a("#fc_Group_form, #fc_User_form").find("input:checkbox"),c.not("[id*=fc_Group_m_], [id*=fc_Group_t_]").prop("checked",!1),c.filter("[id*=fc_Group_m_], [id*=fc_Group_t_]").prop("checked",!1),"group_id"==e.get_id?(a("#fc_Group_name").val(b.name),a("#fc_Group_group_id").val(b.group_id),
a.each(b.system_permissions,function(b,c){a("#fc_Group_"+c).prop({checked:!0})}),a.each(b.module_permissions,function(b,c){a("#fc_Group_m_"+c).prop({checked:!0})}),a.each(b.template_permissions,function(b,c){a("#fc_Group_t_"+c).prop({checked:!0})}),a("div#fc_members").html(b.members)):(a("#fc_User_name").val(b.username).prop("name",b.username_fieldname),a("#fc_User_user_id").val(b.user_id),a("input[name=username_fieldname]").val(b.username_fieldname),a("#fc_User_display_name").val(b.display_name),
a("#fc_User_email").val(b.email),a("#fc_User_password, #fc_User_password2").val(""),a("#fc_User_active_user").prop({checked:b.active}),a("#fc_init_page").val(b.initial_page),a("#fc_init_page_param").val(b.initial_page_param),a("#fc_User_home_folder option").prop({selected:!1}).filter('[value="'+b.home_folder+'"]').prop({selected:!0}),a.each(b.groups,function(b,c){a("#fc_User_groups_"+c).prop({checked:!0})})),return_success(d.process,b.message)):return_error(d.process,b.message)}})})})}})(jQuery);
function validateUserAdd(a){a.find("input:text").each(function(){var a=$(this).val(),c=$(this).prop("rel");"email"!=c&&a.length>c?$(this).removeClass("fc_invalid").addClass("fc_valid"):"email"==c&&isValidEmailAddress(a)?$(this).removeClass("fc_invalid").addClass("fc_valid"):$(this).addClass("fc_invalid").removeClass("fc_valid")});var e=a.find("input:password").eq(0).val(),d=a.find("input:password").eq(1).val();e==d&&5<e.length?a.find("input:password").removeClass("fc_invalid").addClass("fc_valid"):
a.find("input:password").addClass("fc_invalid").removeClass("fc_valid");0<a.find("#fc_group input:checked").size()?a.find("#fc_group").addClass("fc_valid").removeClass("fc_invalid"):a.find("#fc_group").removeClass("fc_valid").addClass("fc_invalid");0<a.find(".fc_invalid").size()?$(".ui-dialog-buttonpane .submit").fadeOut(700):$(".ui-dialog-buttonpane .submit").fadeIn(700)}
jQuery(document).ready(function(){$("input[class*=set_advanced___]").set_individual_buttons();$(".fc_group_list").children("li").set_list_click();$(".fc_user_list").children("li").set_list_click({get_url:CAT_ADMIN_URL+"/users/ajax_get_user.php",activity_message:"Loading user",addOnly:$(".fc_addUser"),modifyOnly:$(".fc_modifyUser"),get_id:"user_id"});$("#fc_list_add").click(function(a){a.preventDefault();a=$(this);$("#fc_list_overview").children("li").removeClass("fc_active");a.addClass("fc_active");
$(".fc_modifyGroup, .fc_modifyUser").hide();$(".fc_addGroup, .fc_addUser").show();$("#fc_Group_form, #fc_User_form").find("input:checkbox").prop("checked",!1);$("#fc_User_form select > option:first").prop("selected",!0);$('#fc_init_page > option[value="start/index.php"]').prop("selected",!0);$("#fc_init_page").val("start/index.php");$("#fc_Group_name, #fc_Group_group_id, #fc_User_form input:text, #fc_User_form input:password").val("").filter("#fc_Group_name").focus()}).click();$("#fc_Group_form input:reset, #fc_User_form input:reset").click(function(a){a.preventDefault();
$("#fc_lists_overview").find(".fc_active").click()});$("input[name=addGroup], input[name=saveGroup]").click(function(a){a.preventDefault();a=$(this);var e=a.closest("form"),d={_cat_ajax:1};templates=[];modules=[];d[a.prop("name")]=a.val();e.find("input[type=checkbox]:checked, input[type=text], #fc_Group_group_id").map(function(){var a=$(this).prop("name"),c=$(this).val();return"module_permissions[]"==a?d.module_permissions=modules.push(c):"template_permissions[]"==a?d.template_permissions=templates.push(c):
d[a]=c});d.module_permissions=modules;d.template_permissions=templates;console.log(d);$.ajax({type:"POST",context:a,url:CAT_ADMIN_URL+"/groups/ajax_save_group.php",dataType:"JSON",data:d,cache:!1,beforeSend:function(a){a.process=set_activity("Saving group")},success:function(a,c,d){!0===a.success?(return_success(d.process,a.message),"saved"==a.action?$("#fc_list_overview").children(".fc_active").children(".fc_groups_name").text(a.name):$('<li class="fc_group_item icon-users fc_border fc_gradient1 fc_gradient_hover"><span class="fc_groups_name">'+
a.name+'</span><input type="hidden" name="group_id" value="'+a.id+'" /></li>').appendTo("#fc_list_overview").set_list_click().click()):return_error(d.process,a.message)}})});$("input[name=addUser], input[name=saveUser]").click(function(a){a.preventDefault();a=$(this);var e=a.closest("form"),d={_cat_ajax:1,home_folder:$("#fc_User_home_folder option:selected").val()},b=[];d[a.prop("name")]=a.val();e.find("input[type=checkbox]:checked, input:text, input:password, select, #fc_User_user_id, #fc_User_fieldname").map(function(){var a=
"groups[]"==$(this).prop("name")?"groups":$(this).prop("name");return d[a]="groups[]"==$(this).prop("name")?b.push($(this).val()):$(this).val()});d.groups=b;$.ajax({type:"POST",context:a,url:CAT_ADMIN_URL+"/users/ajax_save_user.php",dataType:"JSON",data:d,cache:!1,beforeSend:function(a){a.process=set_activity(cattranslate("Saving user"))},success:function(a,b,d){!0===a.success?(return_success(d.process,a.message),"saved"==a.action?($("#fc_User_fieldname").val(a.username_fieldname),$("#fc_User_name").prop("name",
a.username_fieldname),$("#fc_list_overview").children(".fc_active").children(".fc_display_name").text(a.display_name),$("#fc_list_overview").children(".fc_active").children(".fc_list_name").text(a.user_name)):$('<li class="fc_group_item icon-user fc_border fc_gradient1 fc_gradient_hover"><span class="fc_display_name">'+a.display_name+'</span><br/><span class="fc_list_name">'+a.username+'</span><input type="hidden" name="user_id" value="'+a.id+'" /></li>').appendTo("#fc_list_overview").set_list_click({get_url:CAT_ADMIN_URL+
"/users/ajax_get_user.php",activity_message:"Loading user",addOnly:$(".fc_addUser"),modifyOnly:$(".fc_modifyUser"),get_id:"user_id"}).click()):return_error(d.process,a.message)}})});$("#fc_removeGroup, #fc_removeUser").click(function(a){a.preventDefault();a="fc_removeUser"==$(this).prop("id")?"user":"group";var e={id:"group"==a?$("#fc_Group_group_id").val():$("#fc_User_user_id").val()},d=$("#fc_list_overview").children(".fc_active");dialog_confirm("Do you really want to delete this "+a+"?","Removing "+
a,CAT_ADMIN_URL+("group"==a?"/groups/ajax_delete_group.php":"/users/ajax_delete_user.php"),e,"POST","JSON",!1,function(a,c,d){a=$(this);1==$("#fc_list_overview").children("li").size()?$("#fc_list_add").click():a.is(":last-child")?a.prev("li").click():a.next("li").click();a.remove()},d)});$("ul.fc_groups_tabs").find("a").click(function(a){a.preventDefault();a=$(this);var e=a.closest("ul").find("a").not(a),d=a.prop("href"),b=$(".fc_toggle_tabs");e.removeClass("fc_active");a.addClass("fc_active");b.hide();
$(d.substring(d.indexOf("#"))).show()}).filter(":first").click()});
